spring.application.name=FFEOE-BaseDatos
# MariaDB Connection
server.port=9000
spring.datasource.url=jdbc:mariadb://localhost:3306/toner_db
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG

# Spring Data REST
spring.data.rest.base-path=/api
